# -*- coding: utf-8 -*-
"""TI__Aula 4__Intro_Python__2021-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S_tniKfRTiaKszeefZJOA-MNcRAlhuF-
"""

print("100000") # printar Processos Gerenciais na tela (2021-2)

carro = 1032.56
print(type(carro))

carne = "frango"
acompanhamento = " com fritas"
print(acompanhamento)

nome = "Ana"
idade = 28
altura = 1.78
print (nome, "tem", idade, "anos e", altura, "de altura")

numero1 = 27.8
numero2 = 53.2
numero3 = 74
resultado = (numero1 - numero2) / numero3
print(resultado)

# ferramenta para investimento

# Criar variável popupança
poupanca = 25000
juros = 1.0423
periodo=7
resultado = poupanca*juros**periodo 
print(resultado)

valor_corolla = 100000
valor_landrover = 90000
if valor_corolla > valor_landrover:
    print("Corolla e mais caro")
else:
    print("Land Rover e mais caro")

idade=25
maioridade=18
if idade < maioridade:
	print("Menor de idade")
else:
	print("Adulto")

nome = input("Escreva seu nome:")
idade = input("Escreva sua idade:")
altura = input("Escreva sua altura:")

print(nome+" tem "+idade+" anos de idade"+"e "+altura+" de altura.")

import matplotlib.pyplot as plt

x=[250,240,300,120,200]
estados=["Processos Gerenciais", "Administração", "Contabilidade", "Adm Pública", "Atuariais"]
plt.pie(x,labels=estados)

plt.title("Alunos de Graduação UFF/Faculdade Adm e Empreendedorismo")
plt.show()

import matplotlib.pyplot as plt

x = ["1o Trimestre", "2o Trimestre", "3o Trimestre", "4o Trimestre"]
y = [30000,50000,40000,90000]

plt.title("Faturamento Fintech")

plt.xlabel("Trimestre/2020")
plt.ylabel("Faturamento Vendas")

plt.plot(x, y, color="k", linestyle="--")

plt.show()

